### ISSUE TITLE
Adds support to coc.nvim autocomplete

### ISSUE THREAD

**Issue by rafaeldelboni** [clktmr/vim-gdscript3#1]
coc.nvim is an Intellisense engine for vim8 & neovim and is one of the biggest plugins for autocompletion these days. https://github.com/neoclide/coc.nvim

Some examples of other plugins adding coc.nvim support:

- [async-clj-omni](https://github.com/clojure-vim/async-clj-omni/commit/553da607fee342e394ad49aeceb4305915e6bc60)
- [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim/pull/461/files)

**Comment by GordianDziwis** [comment]
Coc supports omnicompletion, so it does work out of the box. Or do you refer to the [Godot VSCode plugin](https://github.com/godotengine/godot-vscode-plugin)? Which could be forked as an [coc extensions](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions).

**Comment by rafaeldelboni** [comment]
Mine is not working, I need to do C-x, C-o to get auto completion, maybe I'm doing something wrong.

Yeah I can't wait for 3.2 to get LSP support, will be a game changer.
