### ISSUE TITLE
Autocomplete erases text (using CoC)

### ISSUE THREAD

**Issue by avahe-kellenberger** [clktmr/vim-gdscript3#10]
When I press enter to select an autocomplete option,
the text is added then immediately removed.

If I exit to normal mode and undo,
the text is placed back.

This is using the default config for `coc-nvim`,
following their setup instructions. This *does not* happen for any other language I've tried with CoC.

---

If any further info is required please let me know. This makes the plugin almost unusable for me

**Comment by clktmr** [comment]
This is either a bug in Godot's language server or CoC.  This plugin
doesn't do completion anymore.  Try using other versions of Godot/CoC or
a different LSP Client than CoC.

Maybe @rafaeldelboni has a solution?  AFAIK he is also using CoC for
completion.

**Comment by rafaeldelboni** [comment]
I remember having some different behavior from godot lsp and others lsp, probably is their server implementation, but since they will rewrite everything in version 4.0 maybe worth testing with diferent godot versions.

But sorry I don't use godot that much anymore.

**Comment by avahe-kellenberger** [comment]
Thanks for the feedback. If this plugin is not the cause we can close the issue, but I'll continue to document my findings here for anyone else who may need it

**Comment by avahe-kellenberger** [comment]
Alright, got it working after some investigation.

I added this to my `~/.config/nvim/after/ftplugin/gdscript3.vim`:
```viml
inoremap <expr> <CR> complete_info().selected != -1 ?
            \ (coc#expandable() ?  "\<C-y>" : "\<C-y><Esc>a") : "\<C-y>"
```

Source: https://github.com/godotengine/godot/issues/34523#issuecomment-674573792

But this didn't seem to resolve it.
I was able to get it working by using the minimal vim config found here: https://github.com/neoclide/coc.nvim/issues/2955

I bisect disabled my vim plugins till I found the culprit to be [tmsvg/pear-tree](https://github.com/tmsvg/pear-tree).
I don't know why this is happening, but I've just disabled the plugin for now.

EDIT: `let g:pear_tree_ft_disabled = [ "gdscript3" ]` will disable this plugin just for this filetype.
